import { Teko } from "next/font/google";
import "./globals.css";
import Nav from "../../components/Nav";


const teko = Teko({ subsets: ["latin"] });

export const metadata = {
  title: "Star Wars",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={teko.className}>
        <Nav/>
        {children}
      </body>
    </html>
  );
}
